export const ACTIONS = {
  CREATE_EXTERNAL_ACCOUNT: "CREATE_EXTERNAL_ACCOUNT",
  CREATE_CONTRACT_ACCOUNT: "CREATE_CONTRACT_ACCOUNT",
  NODE_REGISTERED: "NODE_REGISTERED",
  MUTATE_CONTRACT_DATA: "MUTATE_CONTRACT_DATA",
  MINING_REWARD: "MINING_REWARD",
  INSTANT_MESSAGE: "INSTANT_MESSAGE",
  TRANSACTION_EXTERNAL_ACCOUNT: "TRANSACTION_EXTERNAL_ACCOUNT",
  TRANSACTION_CONTRACT_ACCOUNT: "TRANSACTION_CONTRACT_ACCOUNT"
};
